### ISSUE TITLE
BUG: module ``'urllib'`` has no attribute ``'request'``

### ISSUE THREAD

**Issue by jtodev** [acoular/acoular#479]
### Version Dependencies

Python 3.13.5
Acoular 25.04
macOS 14.7.6 (23H626)

### Bug Description

The module ``'urllib'`` has no attribute ``'request'``.

``urllib.request`` is often used in the Acoular source code.

### Reproducible Code

```python
from pathlib import Path
import urllib

calib_file = Path('../data/example_calib.xml')
url = 'https://github.com/acoular/acoular/raw/master/examples/data/example_calib.xml'

urllib.request.urlretrieve(url, calib_file)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<python-input-2>", line 7, in <module>
    urllib.request.urlretrieve(url, calib_file)
    ^^^^^^^^^^^^^^
AttributeError: module 'urllib' has no attribute 'request'
```

### Issue Severity

Medium: It affects my work, but I can find a workaround.

**Comment by esarradj** [comment]
You need to say `import urllib.request` instead of `import urllib`. I guess the latter never worked. This problem was introduced in #307.

I suggest we need a PR for patching #307.

New examples should always use `import urllib.request`

**Comment by artpelling** [comment]
Closed by #486
